project:
  type: website
  output-dir: docs

website:
  title: "Hanne Oberman"
  navbar:
    title: false
    background: dark
    search: true
    right:
      - href: index.qmd
        text: Home
      - about.qmd
      - research.qmd
  page-footer: 
    left: "H.I. Oberman, MSc" 
    right: 
      - icon: github
        href: https://github.com/hanneoberman
      - icon: twitter 
        href: https://twitter.com/hioberman
      - icon: mastodon
        href: https://mastodon.social/@oberman
      - icon: "{{< fa brands fa-orcid >}}"
        href: https://orcid.org/0000-0003-3276-2141
  open-graph: true
  twitter-card: true


format:
  html:
    theme: 
      light: lux
      dark: [lux, theme-dark.scss]
    css: styles.css
    toc: true

editor: visual

