project:
  type: website
  output-dir: docs

website:
  title: "Hanne Oberman"
  description: "Personal website of Hanne Oberman"
  repo-url: https://github.com/hanneoberman/hanneoberman.github.io
  navbar:
    logo: images/avatar.png
    title: false
    background: dark
    foreground: light
    left: 
      - href: index.qmd
        text: Hanne Oberman
    right:
      - about.qmd
      - research.qmd
      - icon: bi-box-arrow-up-right
        href: https://hanneoberman.github.io/CV/HanneOberman.html
        text: CV
      - icon: bi-box-arrow-up-right
        href: https://hanneoberman.github.io/presentations
        text: Talks
      - icon: bi-box-arrow-up-right
        href: https://github.com/hanneoberman
        text: Code
    search: true
  page-footer: 
    right: 
      - icon: cc-circle
        text: "H.I. Oberman" 
  open-graph: true
  twitter-card: true
  favicon: logo.png
email-obfuscation: javascript
css: styles.css
format:
  html:
    theme: 
      light: [lux, theme-light.scss]
    css: styles.css
    toc: true
    toc-depth: 2
    toc-title: "Contents"
    link-external-newwindow: true
    include-in-header:
      - includes.html
    page-layout: full
