project:
  type: website
  output-dir: docs

website:
  title: "Hanne Oberman"
  navbar:
    title: false
    background: primary
    search: true
    right:
      - href: index.qmd
        text: Home
      - about.qmd
      - research.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

