project:
  type: website

website:
  title: "website"
  navbar:
    title: false
    background: primary
    search: true
    right:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

